//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSchedule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uniScheduleDBEntities : DbContext
    {
        public uniScheduleDBEntities()
            : base("name=uniScheduleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbClassroom> tbClassroom { get; set; }
        public virtual DbSet<tbDays> tbDays { get; set; }
        public virtual DbSet<tbDegree> tbDegree { get; set; }
        public virtual DbSet<tbFieldsOfStudy> tbFieldsOfStudy { get; set; }
        public virtual DbSet<tbFloor> tbFloor { get; set; }
        public virtual DbSet<tbGroups> tbGroups { get; set; }
        public virtual DbSet<tbHours> tbHours { get; set; }
        public virtual DbSet<tbInstructors> tbInstructors { get; set; }
        public virtual DbSet<tbSchedule> tbSchedule { get; set; }
        public virtual DbSet<tbSubjects> tbSubjects { get; set; }
        public virtual DbSet<tbSubjectsInstructors> tbSubjectsInstructors { get; set; }
        public virtual DbSet<tbTypesClassroom> tbTypesClassroom { get; set; }
        public virtual DbSet<tbTypesSubjects> tbTypesSubjects { get; set; }
        public virtual DbSet<tbYearOfStudy> tbYearOfStudy { get; set; }
    }
}
