//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClassroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbClassroom()
        {
            this.tbSchedule = new HashSet<tbSchedule>();
        }
    
        public int id { get; set; }
        public string Number { get; set; }
        public string NameClass { get; set; }
        public short Size { get; set; }
        public int FloorId { get; set; }
        public int TypesClassroomId2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSchedule> tbSchedule { get; set; }
        public virtual tbFloor tbFloor { get; set; }
        public virtual tbTypesClassroom tbTypesClassroom { get; set; }
    }
}
