//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDays
    {
        public int id { get; set; }
        public System.DateTime Days_ { get; set; }
        public int IdSubInst2 { get; set; }
        public int HoursId { get; set; }
    
        public virtual tbHours tbHours { get; set; }
        public virtual tbSubjectsInstructors tbSubjectsInstructors { get; set; }
    }
}
