//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSubjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSubjects()
        {
            this.tbSchedule = new HashSet<tbSchedule>();
            this.tbSubjectsInstructors = new HashSet<tbSubjectsInstructors>();
            this.tbSubjects1 = new HashSet<tbSubjects>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int SubjectsId_ { get; set; }
        public int TypesSubjectsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSchedule> tbSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSubjectsInstructors> tbSubjectsInstructors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSubjects> tbSubjects1 { get; set; }
        public virtual tbSubjects tbSubjects2 { get; set; }
        public virtual tbTypesSubjects tbTypesSubjects { get; set; }
    }
}
